Status update(s)
TrumpTracker/trumptracker.github.io pull request #74
Opened 2017-01-21 01:22 UTC by donawick

https://news.vice.com/story/trump-signed-a-stack-of-executive-orders-moments-after-he-became-president

2017-01-21 02:18 UTC, alanfriedman requested changes

2017-01-21 02:18 UTC, alanfriedman commented on _data/data.yaml
> +            status: Started
I can't find any reports of him starting this.

2017-01-21 02:18 UTC, alanfriedman commented on _data/data.yaml
> +            status: Complete
I can't find any reports of him starting this.

2017-01-21 02:26 UTC, donawick commented on _data/data.yaml
> +            status: Started
http://www.politifact.com/truth-o-meter/promises/trumpometer/promise/1357/defund-planned-parenthood/

It's in the works for this Sunday.

2017-01-21 02:28 UTC, donawick commented on _data/data.yaml
> +            status: Complete
You're correct, it seems as though it hasn't been confirmed. Although it seems he may end up taking $1 for his salary.

2017-01-21 02:34 UTC, alanfriedman commented on _data/data.yaml
> +            status: Complete
Ok let's keep this as notStarted until progress is made.

2017-01-21 02:34 UTC, alanfriedman commented on _data/data.yaml
> +            status: Started
Ok thanks

2017-01-23 14:05 UTC, MrLuit commented
The status for started is 'inProgress' not 'Started' :)

2017-02-03 13:59 UTC, VirenMohindra commented
This is now deprecated, if you'd like to contribute, please create a new PR with the new `data.yaml`.

Thank you!

2017-02-03 13:59 UTC, closed without merging